server:
  port: 8091
twillio:
  from_number: '+18586304908'
weather:
  apikey: 26eb4d58dbff0c98b1f641509904c35e
  url: api.openweathermap.org/data/2.5/weather
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: https://ambika-discovery-server.herokuapp.com/

spring:
  application:
    name: SmsService